from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def write_report(
    owner: str,
    repo: str,
    issues: list[dict[str, Any]],
    output_path: str | Path = "analyze-report.md",
) -> str:
    """
    Generate a Markdown analyze report for a GitHub repository.

    Parameters:
    - owner: Repository owner/organization
    - repo: Repository name
    - issues: List of normalized issue dictionaries
    - output_path: Destination filepath for the markdown report

    Returns:
    - Path string of the written report file
    """
    out_file = Path(output_path)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = []
    # Title & Timestamp
    lines.append(f"# Analyze Report: {owner}/{repo}")
    lines.append("")
    lines.append(f"*Generated by kgiit v1.0.0 at: {timestamp}*")
    lines.append(f"*Total Open Issues: {len(issues)}*")
    lines.append("")

    # Summary Table
    lines.append("## Issues Summary")
    lines.append("")
    lines.append("| # | Title | Labels | Comments |")
    lines.append("|---|-------|--------|----------|")

    if not issues:
        lines.append("| - | *No open issues found* | - | - |")
    else:
        for issue in issues:
            num = f"#{issue.get('number', '')}"
            title = issue.get(
                "title", "").replace(
                "|", "\\|")  # Escape pipes in markdown table

            raw_labels = issue.get("labels", [])
            if raw_labels:
                labels_str = ", ".join(f"`{label}`" for label in raw_labels)
            else:
                labels_str = "*none*"

            comments = issue.get("comments", 0)
            lines.append(f"| {num} | {title} | {labels_str} | {comments} |")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Issue Details Section
    lines.append("## Issue Details")
    lines.append("")

    if not issues:
        lines.append("*No open issue details available.*")
        lines.append("")
    else:
        for issue in issues:
            num = issue.get("number", "")
            title = issue.get("title", "")
            url = issue.get("url", "")
            created_at = issue.get("created_at", "")
            body = issue.get("body")

            lines.append(f"### Issue #{num}: {title}")
            lines.append("")
            lines.append(f"- **URL**: [{url}]({url})")
            lines.append(f"- **Created At**: {created_at}")

            raw_labels = issue.get("labels", [])
            if raw_labels:
                labels_formatted = ", ".join(f"`{lbl}`" for lbl in raw_labels)
                lines.append(f"- **Labels**: {labels_formatted}")

            lines.append("")
            lines.append("#### Description")
            lines.append("")
            if body and body.strip():
                lines.append(body.strip())
            else:
                lines.append("*No description provided.*")

            lines.append("")
            lines.append("---")
            lines.append("")

    content = "\n".join(lines)

    # Ensure parent directory exists if a path with subdirectories was passed
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(content, encoding="utf-8")

    return str(out_file)
